name: Install dependencies and build app
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: composer:v2

      - name: Instalar dependências do Composer
        run: composer install --no-interaction --no-dev --optimize-autoloader

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar dependências e compilar vite
        run: npm install && npm run build

      - name: Criar artefato node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

      - name: Criar artefato build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public
